### ISSUE TITLE
Change name to addon_catalog

### ISSUE THREAD

**Issue by michaeltwofish** [habari-extras/addon_catalog#16]
(was "Change name to addon_directory") Because it's not just for plugins.

Because "catalog" sounds better.

**Comment by mikelietz** [comment]
As soon as screenshots work, yes.

**Comment by mikelietz** [comment]
Title edited.

**Comment by ringmaster** [comment]
Completed as of @7138fd9d08c1b9af99d7f223d36393df30f26fbd
