### ISSUE TITLE
Determine minimum level of functionality for release

### ISSUE THREAD

**Issue by miklb** [habari-extras/addon_catalog#20]
While there are I'm sure a plethora of features that everyone wants to see in the addons directory, there should be a baseline set for the initial milestone so that the community can begin using it.

Perhaps a single issue discussion is the place to do it, or a new issue for each feature and then those assigned to a milestone.

**Comment by miklb** [comment]
A milestone of 1.0 has been created. As suggested in the description, this milestone should really only be used for the baseline set of features needed for the directory to be functional enough to go live. I'm sure once it's live, both end users and developers submitting their work will find or want additional features.

**Comment by miklb** [comment]
Morydd has a good document outlining why we need an addon directory and features for both plugins and themes. [his google doc](https://docs.google.com/a/miklb.com/document/d/1xZBwJIDBYR-1GFCIBnQfDHCkz0rkLWV27JGxiBOS2is/edit)

From discussions with mikelietz in IRC, support for theme screenshots and working download links seem to be to major missing components in the working code. An issue already existed for screenshots, one will be opened for download links.

**Comment by miklb** [comment]
Also see the original outline from the [working group wiki page](http://wiki.habariproject.org/en/Working_groups/addon_directory) referenced in #6

**Comment by miklb** [comment]
Additional note - most of the work on this has been done in forks and repos outside this initial "official" repo. That code is currently being refactored and will be merged back into this one in the coming (days?). At that point, this repo will be renamed addons_catalog, to reflect both plugins and themes. At that time, the url for this project will change. At that time it may be easier to fully determine what is working and what is still needed outside the items already raised in separate issues and assigned the 1.0 milestone.

**Comment by michaeltwofish** [comment]
As per #16 it's now been renamed to addon_directory.

**Comment by mikelietz** [comment]
Can this be closed as the site is now live?

**Comment by miklb** [comment]
I would think so.
