### ISSUE TITLE
Functional Download Link

### ISSUE THREAD

**Issue by miklb** [habari-extras/addon_catalog#21]
Currently there is not working download link generated.

**Comment by miklb** [comment]
See the [Github Packager Class](https://gist.github.com/1339633) gist for reference.

**Comment by Konzertheld** [comment]
Unfortunately, the class is outdated because of the new GitHub API.

**Comment by Konzertheld** [comment]
There's work going on: https://github.com/habari-extras/addon_catalog/pull/27/

We still need to get existing tags.
