### ISSUE TITLE
Document Adding to the  catalog

### ISSUE THREAD

**Issue by miklb** [habari-extras/addon_catalog#22]
Outline how plugin and theme authors submit their work to the catalog. See how the [jQuery project outlines](http://plugins.jquery.com/docs/publish/) the publishing process for reference.

**Comment by michaeltwofish** [comment]
Started at http://wiki.habariproject.org/en/Addon_catalog

**Comment by Konzertheld** [comment]
I think this is done now. If you don't think so, please reopen and let me know where to be more detailed.
