### ISSUE TITLE
Unknown tag format

### ISSUE THREAD

**Issue by michaeltwofish** [habari-extras/addon_catalog#32]
Your tag (refs/heads/fixit) is in an unsupported format. Please re-tag it with the specified format for inclusion in the directory.<br>If you were not tagging it for the directory this issue can be ignored.

**Comment by Konzertheld** [comment]
...can be ignored.

**Comment by Konzertheld** [comment]
Maybe not. This issue should not have occured as the push was for a branch.

**Comment by Konzertheld** [comment]
@mikelietz takes care of this in the intake plugin where it comes from.
