### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by mikelietz** [habari-extras/addon_catalog#4]
So you go to hp.o/whatever ... what will you find? Snapshot of recent activity? Quick explanation of what the thing is and does and how to navigate it? Screenshot gallery of themes?

Needs a rewrite rule.

**Comment by michaeltwofish** [comment]
There's now a rewrite rule for the landing page. The landing page simply links to pages for each type of addon.

**Comment by miklb** [comment]
This should probably be fleshed out for initial release, then wish-list once it's up and running. Would help anyone who is helping flesh out a design as well.

**Comment by chrisjdavis** [comment]
This should be addressed.
